### PR TITLE
Bug Patch and Feature Enhancement

### PR DESCRIPTION
**Pull request by BatterySmooth**
Patch to recent security update preventing URIs from being opened in new tabs and feature enhancement.

Summary of changes:

- Added a direct download link on the ending screen to allow the csv file to be downloaded directly. The original method was no longer allowed following a recent security patch preventing URIs from being opened in a new tab.
- Added the ability to pre-populate some of the fields via a URL query. These values are extracted, then the page redirects to main.html and uses the variables in the query to populate and mark respective text boxes as read-only.
- Changed the keys to press from the left and right arrow keys to E and I. Instructions changed to advise of this.

### CODE REVIEW

**Comment by BatterySmooth** [comment]
Also forgot a few other changes;

- Changed the browser warning to only show when the browser being used is not Firefox (detected via [ducktyping](https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser/9851769)).
- Added a tab icon to show on the browser tab.

**Comment by docksteaderluke** [comment]
Thanks for your pull request! Unfortunately, I came across a small problem when first testing it out:

Switching the keys to 'e' and 'i' is good, but problematic for new users because of Firefox's "Search for text when you start typing" setting (Settings -> General -> Browsing), which is enabled by default. In short, it causes the Find dialog to open and captures all keyboard input preventing ANT from receiving keystrokes (see screenshot). This will need to be fixed, or an explanation of how to disable this setting will need to be added to the instructions before I can accept this pull request.

I will continue looking through this and let you know if I have any more thoughts/questions.

Screen Shot 2021-12-14 at 10 50 48

**Comment by BatterySmooth** [comment]
Hi Luke,

Thank you for your response! In all honesty I'd forgotten about this feature, nice catch! Would you like me to change those back and resubmit?

**Comment by BatterySmooth** [comment]
Changing the keys back to left and right arrow to resubmit and add in guide for changing keys and checking 'search to type'

**Pull request closed without merging**
