### PR TITLE
Bug Patch and Feature Enhancement

### PR DESCRIPTION
**Pull request by BatterySmooth**
Patch to recent security update preventing URIs from being opened in new tabs and feature enhancement.

Summary of changes:

- Added a direct download link on the ending screen to allow the csv file to be downloaded directly. The original method was no longer allowed following a recent security patch preventing URIs from being opened in a new tab.
- Added the ability to pre-populate some of the fields via a URL query. These values are extracted, then the page redirects to main.html and uses the variables in the query to populate and mark respective text boxes as read-only.
- Added instructions on changing the keys and disabling 'Type to Search' if these are changed.
- Changed the browser warning to only show when the browser being used is not Firefox (detected via [ducktyping](https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser/9851769)).
- Added a tab icon to show on the browser tab.

### CODE REVIEW

**Comment by docksteaderluke** [comment]
I'm going to commit some changes to this PR as I go through it. Feel free to comment/discuss them as needed.

**Comment by BatterySmooth** [comment]
Hi Luke,

Will do, thanks again! If you have any questions then let me know.

**Comment by docksteaderluke** [comment]
Any reason the "Clear" button was removed from the form page? I _think_ that was a requested function in the original app.

**Comment by BatterySmooth** [comment]
Originally I had issues with it clearing read-only text boxes that were populated by the URL query feature. I was going to revisit this but didn't in the end as it wasn't required by for the set-up it was being used in. Would you like me to revisit this?

**Comment by docksteaderluke** [comment]
If it's an issue with the read-only text fields, we could just make them editable. Might be a nice option even if they are initially populated by the URL params.

**Comment by docksteaderluke** [comment]
Alternatively, that button could just reload the index.html page without the URL params if those fields need to be read-only. What is the reasoning for the read-only fields?

**Comment by BatterySmooth** [comment]
Ah, I was looking onto clearing only readable fields, but refreshing the browser is a much better idea!
The idea with the URL Pre-population is that a link can be generated for a participant in such a way as to prevent them changing these values.

Having the Clear button refresh the page would work. I'll get that added back in now

**Comment by docksteaderluke** [comment]
That makes more sense. To be clear, the "Clear" button should only reset the non-readonly fields, right? Maybe "reset" is better terminology. My first instinct was that it shouldn't just reload, but redirect to index.html without the URL parameters, but then that effectively gives users the ability to edit the readonly fields. So maybe we stick with what you have but change the wording to reset. I'll get on that.

**Comment by BatterySmooth** [comment]
Originally the purpose of using index.html and main.html (with a redirect) was to prevent editing of the URL to change the fields, but in either case refreshing the page will keep the read-only fields and clear the others. The values to populate the fields are stored in the session storage.

**Comment by docksteaderluke** [comment]
Ah... couldn't figure out why that was done like that. I can revert that change if you think it's necessary.

**Comment by docksteaderluke** [comment]
On another note: The new CSV saving feature seems to work really well! I'm thinking we can retire the old method of downloading entirely (unless you know of a valid reason to do otherwise). The only thing I would like to do first is get the new CSV method working for both the Raw Data _and_ the Summary Data (currently only does Raw).

**Comment by BatterySmooth** [comment]
It's up to you, I still have the original copy with the redirect which I can use.
The old method of saving the CSV was blocked from an update as far as I can tell. I tried to replicate this for the summary data, but was having difficulty getting it to produce any data - since the summary data wasn't needed for my use-case, I didn't dive too deeply into this I'm afraid.

Implementing it should be super easy though, there's a js function in export.js (I think) for generating download links that takes in an URI and spits out a download link.

**Comment by docksteaderluke** [comment]
Sounds good — I can go back through the commits and grab the old index.html file so don't worry about that. Since others use this as well, I'll also work on getting the Summary file downloading correctly. Then I'll commit all of that here and merge the PR.

Curious as to your involvement with the CRSD? We originally built this over 10 years ago (with minimal updates) and I'm shocked it's still in use!

**Comment by BatterySmooth** [comment]
Stellar! Thanks for your support.
I feel the same way - I'm surprised it's still being supported! My other half is using this as a measure in a psychology dissertation and needed a short and approved ANT. This was the best option and I've been wanting to dip my hands into HTML/CSS/JS for a while, so took this as an excuse.

**Comment by docksteaderluke** [comment]
Awesome! So glad it's still being used!

I just pushed those changes — please take a look and let me know if anything is missing.

**Comment by BatterySmooth** [comment]
Brill! Thanks again for this test - it's been crucial.
I'll have a look through them and do some cleaning up too - I'm sure there are some old functions that can be cleared out!

I also noticed in trialSet.js in config, the following was disabled: [4,'incongruent','DOWN','DOWN','L','R'] - was there a reason for this that you can recall?

**Comment by docksteaderluke** [comment]
Honestly, not that I can recall. It's likely an error. Code comments elsewhere refer to 32 objects in a trialSet and there are only 31 without that line so it's probably safe to uncomment it.

**Comment by docksteaderluke** [comment]
Just tested it and can confirm that it's definitely missing from the data export too. Might be worth getting your other half to look at it too, if this is their expertise.

**Comment by docksteaderluke** [comment]
Any other questions/comments/suggestions? If not I'll merge this PR.

**Comment by BatterySmooth** [comment]
I've re-enabled it, it was actually them that identified it - the validated test should have 32. I've had a glance and I don't see anything else that needs changing or refreshing, all looks good!

**Comment by BatterySmooth** [comment]
Thanks again, working on this has been fun and it's great to chat with you about it!

**Comment by docksteaderluke** [comment]
Nice! And yeah, thanks for the PR — it's great to give it a little update! Cheers!

**Pull request merged**
